### ISSUE TITLE
destroyed includes/OutputPage.pho

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wiki#1]
Shit... hab wohl ausversehen ein find/replace oder so darin gemacht gespeichert, hochgeladen... hab keine originalversion mehr. wiki ist down.

**Comment by phibo23** [comment]
also, es gibt noch eine im ordner wiki_old, die ist aber inhaltlich gleich...

**Comment by TVLuke** [comment]
Das liegt daran glaube ich daran, dass ichs mit der versucgt hab... Evtl.

Philipp notifications@github.com schrieb am Fr., 31. Juli 2015 19:17:

**Comment by TVLuke** [comment]
pascal hat die Uhr zurückgedreht, dinge gehen wieder. Ich hoffe er hat worpress nicht auf vor-virusentfernung gesetzt...
